apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "app.provisionings.fullname" . }}
data:
  grafana.ini: |+
    [users]
    allow_sign_up = false
    auto_assign_org = true
    auto_assign_org_role = Editor

    [auth.proxy]
    enabled = true
    header_name = rancher_access_key
    header_property = username
    auto_sign_up = true

  dashboards.yaml: |+
    - name: RANCHER_MONITORING
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      updateIntervalSeconds: 0 #never
      options:
        path: /var/lib/grafana/rancher-dashboards
    - name: RANCHER_ISTIO_MONITORING
      orgId: 2
      folder: 'istio'
      type: file
      disableDeletion: false
      updateIntervalSeconds: 0 #never
      options:
        path: /var/lib/grafana/rancher-istio-dashboards


  datasources.yaml: |+
    apiVersion: 1

    datasources:
    - name: RANCHER_MONITORING
      type: prometheus
      access: proxy
      basicAuth: false
      editable: false
      isDefault: true
      url: {{ .Values.prometheusDatasourceURL }}
    
    - name: ECHO
      type: prometheus
      access: proxy
      basicAuth: false
      editable: false
      isDefault: false
      url: http://echo.default.svc:80
      jsonData:
          httpHeaderName1: 'rancher_access_key'
          httpHeaderName2: 'rancher_access_secret'
          httpHeaderName3: 'rancher_token'