apiVersion: v1
kind: Pod
metadata:
  name: {{ template "fluentd-tester.fullname" . }}
  labels:
    app: {{ include "fluentd-tester.name" . }}
    chart: {{ template "fluentd-tester.version" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    kubernetes.io/cluster-service: "true"
{{- if .Values.labels }}
{{ toYaml .Values.labels | indent 4 }}
{{- end }}
spec:
  containers:
  - name: "dry-run"
    image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
    imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
  {{- if .Values.command }}
    command: {{ .Values.command }}
  {{ end }}
    volumeMounts:
    - mountPath: /fluentd/etc/config/custom
      name: custom
    - mountPath: /fluentd/etc/config/std
      name: config
  restartPolicy: Never
  volumes:
  - hostPath:
      path: /var/lib/rancher/fluentd/etc/config/custom
    name: custom
  - name: config
    secret:
      secretName: {{ template "fluentd-tester.fullname" . }}