{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "fluentd-tester.fullname" . }}
  labels:
    app: {{ include "fluentd-tester.name" . }}
    chart: {{ template "fluentd-tester.version" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    kubernetes.io/cluster-service: "true"
{{- end -}}
