apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ template "log-aggregator.fullname" . }}
  labels:
    app: {{ include "log-aggregator.name" . }}
    chart: {{ template "log-aggregator.version" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.labels }}
{{ toYaml .Values.labels | indent 4 }}
{{- end }}
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ include "log-aggregator.name" . }}
      chart: {{ template "log-aggregator.version" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "log-aggregator.name" . }}
        chart: {{ template "log-aggregator.version" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ template "log-aggregator.fullname" . }}
      containers:
      - name: log-aggregator
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        securityContext:
          privileged: true
        volumeMounts:
        - name: flexvolume-driver
          mountPath: /flexmnt
        env:
{{ toYaml .Values.env | indent 10 }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
      terminationGracePeriodSeconds: 10
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
      tolerations:
    {{- if .Values.tolerations }}
{{ toYaml .Values.tolerations | indent 8 }}
    {{- end }}
      volumes:
      - name: flexvolume-driver
        hostPath:
          path: {{ .Values.flexVolumeDir }}