apiVersion: v1
kind: ConfigMap
metadata:
  name: kiali-nginx
  namespace: {{ .Release.Namespace }}
  labels:
    app: kiali-nginx
    chart: {{ template "kiali.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  nginx.conf: xxxx
