#
# addon grafana configuration
#
enabled: false
replicaCount: 1
image:
  repository: grafana/grafana
  tag: 5.4.0
  proxy:
    repository: rancher/nginx
    tag: 1.15.8-alpine
ingress:
  enabled: false
  ## Used to create an Ingress record.
  hosts:
    - grafana.local
  annotations:
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  tls:
    # Secrets must be manually created in the namespace.
    # - secretName: grafana-tls
    #   hosts:
    #     - grafana.local
persistence:
  enabled: false
  storageClass: ""
  accessMode: ReadWriteMany
  size: 5Gi
security:
  enabled: false
  secretName: grafana
  usernameKey: username
  passphraseKey: passphrase
nodeSelector: {}
contextPath: /grafana
service:
  annotations: {}
  type: ClusterIP

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      orgId: 1
      url: http://prometheus:9090
      access: proxy
      isDefault: true
      jsonData:
        timeInterval: 5s
      editable: true

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'istio'
      orgId: 1
      folder: 'istio'
      type: file
      disableDeletion: false
      options:
        path: /var/lib/grafana/dashboards/istio

resources: {}