---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ include "fluentd.name" . }}
    chart: {{ template "fluentd.version" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ .Values.config.clusterLoggingSecretName }}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ include "fluentd.name" . }}
    chart: {{ template "fluentd.version" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ .Values.config.projectLoggingSecretName }}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ include "fluentd.name" . }}
    chart: {{ template "fluentd.version" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ .Values.config.sslConfigSecretName }}